spring:
  application:
    name: finance-portfolio
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
        instance-profile: false

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB

  thymeleaf:
    check-template-location: false

server:
  error:
    include-stacktrace: never      # 스택트레이스 노출 차단 (필수)
    include-message: never         # 에러 메시지 노출 차단
    include-exception: false       # 예외 클래스명 노출 차단
    include-binding-errors: never  # 파라미터 바인딩 에러 노출 차단

jwt:
  secret: ${JWT_SECRET_KEY}  # 32자 이상
  access-token-expiration: 900000       # 15분 (ms)
  refresh-token-expiration: 604800000   # 7일 (ms)      

cloudfront:
  enabled: false
---
spring:
  config:
    activate:
      on-profile: local

  # 핫스왑 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 500ms

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio_db?serverTimezone=UTC
    username: root
    password: ${LOCAL_DB_PW}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID} 
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket-name: finportfolio-s3-bucket-local-9806
        cloudfront-domain: dt08rm0613jz4.cloudfront.net
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://db-dev:3306/dev_db?serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID} 
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket-name: finportfolio-s3-bucket-dev-9806
        cloudfront-domain: d24842uv7pd3qd.cloudfront.net

cloudfront:
  enabled: true
  custom:
    header:
      name: X-Custom-Access-Key
      value: ${CF_SECRET_KEY}
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://db-prod:3306/portfolio_db?serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # 운영 서버는 테이블 구조가 변하면 안 되므로 안전하게 체크만 함

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID} 
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket-name: finportfolio-s3-bucket-prod-9806
        cloudfront-domain: d2m4qtzslhorm2.cloudfront.net

cloudfront:
  enabled: true
  custom:
    header:
      name: X-Custom-Access-Key
      value: ${CF_SECRET_KEY}