# S3 설정
cloud.aws.credentials.access-key=AKIAVSROV47HFJDJUIG6
cloud.aws.credentials.secret-key=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
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false

# 버킷 이름
cloud.aws.s3.bucket=finportfolio-s3-bucket-dev-9806