# S3 설정
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.region.instance-profile=false

# 버킷 이름
spring.cloud.aws.s3.bucket=finportfolio-s3-bucket-dev-9806