spring.application.name=finance-portfolio
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
# 파일 변경 감지 주기 설정 (단위: ms)
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=500ms
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

# DB 연결 (환경변수가 없으면 localhost의 3306 포트를 바라봄)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 파일 업로드 경로 설정(나중에 한번에 변경 가능)
file.upload-dir=upload_images

# JPA 설정
# spring.jpa.hibernate.ddl-auto=validate 배포 전 이걸로 변경
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# POST로 온 요청 중 _method=DELETE가 있으면 DELETE 매핑으로 연결해줌
spring.mvc.hiddenmethod.filter.enabled=true