sonar.projectKey=hello6135_finance-portfolio
sonar.organization=ljh-finance
sonar.projectName=Finance Portfolio
sonar.projectVersion=1.0.0

# 분석 대상 설정
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# 제외 대상
# 기존 제외 대상에 정적 자원 추가
sonar.exclusions=**/node_modules/**, dist/**, **/*.test.jsx, **/*.test.js, **/.env, \
 src/assets/**, **/*.png, **/*.jpg, **/*.svg

sonar.coverage.exclusions=**/main.jsx, **/App.jsx, **/api/axios.js, **/*.css \
 src/pages/Post*.jsx, src/api/post*.js

# JavaScript 전용 설정
sonar.javascript.lcov.reportPaths=coverage/lcov.info