sonar.projectKey=hello6135
sonar.organization=ljh-finance
sonar.projectName=Finance Portfolio
sonar.projectVersion=1.0.0

# 분석 대상 설정
sonar.sources=src
sonar.sourceEncoding=UTF-8

# 제외 대상
sonar.exclusions=**/node_modules/**, dist/**, **/*.test.jsx, **/*.test.js, **/.env

# JavaScript 전용 설정
sonar.javascript.lcov.reportPaths=coverage/lcov.info